name: Deploy

on: 
  pull_request:
    branches:
      - feature/deploy_test
env:
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/test-image:${{ github.sha }}
  SERVICE_NAME: cloudrun-bff-morikawa-test
  PORT: 80
  GCP_REGION: us-central1
   
jobs:
#  if_merged:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#    - run: |
#        echo The PR was merged
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref }}
    steps:
      # リポジトリをチェックアウト
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
 
      # GCP 認証
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
 
      # gcloud コマンドの設定
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
 
      # Docker に gcloud コマンドの Credential を使わせる
      - name: 'Configure docker to use the gcloud cli'
        run: gcloud auth configure-docker --quiet
 
      # Docker イメージを作成
      - name: 'Build a docker image'
        run: docker build -t $IMAGE .
 
      # Docker イメージを Container Registry に Push
      - name: 'Push the docker image to Container Registry'
        run: docker push $IMAGE
 
      # Container Registry から Cloud Run へデプロイ
      - name: 'Deploy to Cloud Run'
        run: |
            gcloud run deploy $SERVICE_NAME \
              --image $IMAGE \
              --port $PORT \
              --project $GCP_PROJECT_ID \
              --region $GCP_REGION \
              --platform=managed \
              --allow-unauthenticated \
              --quiet